# proto-file: google3/third_party/cel/spec/proto/cel/expr/conformance/test/suite.proto
# proto-message: cel.expr.conformance.test.TestSuite

name: "expr_value_output_tests"
description: "Value as expected output"
sections {
  name: "basic value"
  description: "Basic value"
  tests {
    name: "basic value test"
    description: "Basic value test"
    output {
      result_value {
        bool_value: true
      }
    }
  }
}