# proto-file: google3/third_party/cel/spec/proto/cel/expr/conformance/test/suite.proto
# proto-message: cel.expr.conformance.test.TestSuite

# The input binding is not used for evaluation, but rather to ensure
# extension registry generation and support for `Any` typed inputs with
# extensions.

name: "protoextension_value_as_input"
description: "Valid proto extension value as input"
sections {
  name: "valid"
  description: "Valid proto extension value as input"
  tests {
    name: "value_extension_input"
    input {
      key: "spec"
      value {
        value {
          object_value {
            [type.googleapis.com/cel.expr.conformance.proto2.TestAllTypes] {
              [cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_nested_ext]: {}
            }
          }
        }
      }
    }
    output {
      result_expr: "true"
    }
  }
}