# proto-file: google3/third_party/cel/spec/proto/cel/expr/conformance/test/suite.proto
# proto-message: cel.expr.conformance.test.TestSuite

name: "context_pb_tests"
description: "Protobuf input tests"
sections {
  name: "valid"
  description: "Valid protobuf input tests"
  tests {
    name: "good spec"
    description: "Valid protobuf input tests"
    input_context {
      context_expr: "TestAllTypes{single_int32: 10}"
    }
    output {
      result_expr: "optional.none()"
    }
  }
}
